export const ACTION_LOG_IN= 'LOG_IN';
export const ACTION_LOG_OUT = 'LOG_OUT';
export const ACTION_LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const ACTION_LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const ACTION_LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const ACTION_SAVE_AUTH_TOKEN = 'SAVE_TOKEN';
export const ACTION_FAKE_AUTH_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c';