export const ACTION_LOAD_CARDS= 'LOAD_CARD';
export const ACTION_LOAD_CARDS_SUCCESS= 'LOAD_CARDS_SUCCESS';

export const ACTION_READY_DISPLAY_CARDS= 'READY_DISPLAY_CARDS';
export const ACTION_SEARCH_CARD= 'SEARCH_CARD';
export const ACTION_SEARCH_NO_DATA= 'SEARCH_NO_DATA';
export const ACTION_RESET_SEARCH_FLAG = 'RESET_SEARCH_FLAG';

export const ACTION_LOAD_CARD_DETAIL = 'LOAD_CARD_DETAIL';
export const ACTION_LOAD_CARD_DETAIL_SUCCESS = 'LOAD_CARD_DETAIL_SUCCESS';

export const ACTION_LOAD_FUNDS = 'LOAD_FUNDS';
export const ACTION_LOAD_FUNDS_SUCCESS = 'LOAD_FUNDS_SUCCESS';

export const ACTION_LOAD_COMMENT_CATEGORIES = 'LOAD_COMMENT_CATEGORIES';
export const ACTION_LOAD_COMMENT_CATEGORIES_SUCCESS = 'LOAD_COMMENT_CATEGORIES_SUCCESS';

export const ACTION_LOAD_ALERTS = 'LOAD_ALERTS';
export const ACTION_LOAD_ALERTS_SUCCESS = 'LOAD_ALERT_SUCCESS';

export const ACTION_LOAD_TRANS = 'LOAD_TRANS';
export const ACTION_LOAD_TRANS_SUCCESS = 'LOAD_TRANS_SUCCESS';

export const ACTION_GET_CARDHOLDER_INFO = 'GET_CARDHOLDER_INFO';
export const ACTION_LOAD_CARDHOLDER_INFO_SUCCESS = 'LOAD_CARDHOLDER_INFO_SUCCESS';

export const ACTION_SAVE_CARDHOLDER_INFO = 'SAVE_CARDHOLDER_INFO';
export const ACTION_SAVE_CARDHOLDER_INFO_SUCCESS = 'SAVE_CARDHOLDER_INFO_SUCCESS';

export const ACTION_GET_CARDHOLDER_HISTORY = 'GET_CARDHOLDER_HISTORY';
export const ACTION_LOAD_CARDHOLDER_HISTORY = 'LOAD_CARDHOLDER_HISTORY';
